baseURL = "https://www.christianwritings.org/"
languageCode = "en"
title = "✟ Christian Writings ✟"
canonifyURLs = true

theme = "hugo-theme-monochrome"
defaultContentLanguage = "en"
enableEmoji = false
paginate = 5
summaryLength = 10
enableGitInfo = true
[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.3


[Params]

[taxonomies]
tag = "tags"

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
    [frontmatter]
        lastmod = ["lastmod", ":git", "date", "publishDate"]
        publishDate = ["publishDate", "date"]
    [markup.goldmark.renderer]
        unsafe = true
