baseURL = "https://www.christianwritings.com/"
languageCode = "en"
title = "✟ Christian Writings ✟"

theme = "hugo-theme-monochrome"
defaultContentLanguage = "en"
enableEmoji = false
paginate = 5

[Params]

[taxonomies]
tag = "tags"

[outputs]
home = ["HTML", "RSS", "JSON"]
