baseURL = "https://www.christianwritings.org/"
languageCode = "en"
title = "✟ Christian Writings ✟"

theme = "hugo-theme-monochrome"
defaultContentLanguage = "en"
enableEmoji = false
paginate = 5
summaryLength = 9

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.3


[Params]

[taxonomies]
tag = "tags"

[outputs]
home = ["HTML", "RSS", "JSON"]
