[[navbar]]
  identifier = "Home"
  name = "Home"
  url = "/"
  weight = 1

[[navbar]]
  identifier = "Bible"
  name = "Bible"
  url = "/bible/"
  weight = 2

[[navbar]]
  identifier = "Apostolic Fathers"
  name = "Apostolic Fathers"
  url = "/apostolic-fathers/"
  weight = 3

[[navbar]]
  identifier = "Support Us"
  name = "Support Us"
  url = "https://www.buymeacoffee.com/christianwr/"
  weight = 4
  